### ISSUE TITLE
Bug: test suite failure in  MACS 3.0.0

### ISSUE THREAD

**Issue by tillea** [macs3-project/MACS#615] opened 2024-01-26 08:54 UTC
**Describe the bug**
When trying to update the Debian package for MACS I get some test suite errors in test step `16.18`.

    ...
    16.17.1 checking callvar PEsample.vcf ...
     ... success!
    16.18.1 checking hmmratac hmmratac_yeast500k_accessible_regions.gappedPeak ...
     ... failed! Difference:
    1,283c1,919
    < chrI      0       700     peak_1  0       .       30      560     0       1       530     30      0       0       0
    < chrI      113420  114870  peak_5  0       .       113440  114700  0       1       1260    20      0       0       0
    < chrI      140480  142080  peak_6  0       .       140760  141740  0       1       980     280     0       0       0
    < chrI      165050  165900  peak_7  0       .       165330  165830  0       1       500     280     0       0       0
    < chrI      181160  181650  peak_8  0       .       181200  181610  0       1       410     40      0       0       0
    < chrI      198460  199140  peak_9  0       .       198660  199090  0       1       430     200     0       0       0
    < chrI      60130   62600   peak_2  0       .       60410   62150   0       1       1740    280     0       0       0
    < chrI      67960   69780   peak_3  0       .       68160   69260   0       1       1100    200     0       0       0
    < chrI      71790   73230   peak_4  0       .       72120   73000   0       1       880     330     0       0       0
    16.18.2 checking hmmratac hmmratac_yeast500k_bedpe_accessible_regions.gappedPeak ...
     ... failed! Difference:
    1,283c1,919
    < chrI      0       700     peak_1  0       .       30      560     0       1       530     30      0       0       0
    < chrI      113420  114870  peak_5  0       .       113440  114700  0       1       1260    20      0       0       0
    < chrI      140480  142080  peak_6  0       .       140760  141740  0       1       980     280     0       0       0
    < chrI      165050  165900  peak_7  0       .       165330  165830  0       1       500     280     0       0       0
    < chrI      181160  181650  peak_8  0       .       181200  181610  0       1       410     40      0       0       0
    < chrI      198460  199140  peak_9  0       .       198660  199090  0       1       430     200     0       0       0
    < chrI      60130   62600   peak_2  0       .       60410   62150   0       1       1740    280     0       0       0
    < chrI      67960   69780   peak_3  0       .       68160   69260   0       1       1100    200     0       0       0
    < chrI      71790   73230   peak_4  0       .       72120   73000   0       1       880     330     0       0       0
    16.18.3 checking hmmratac hmmratac_yeast500k_load_hmm_model_accessible_regions.gappedPeak ...
     ... failed! Difference:
    1,283c1,919
    < chrI      0       700     peak_1  0       .       30      560     0       1       530     30      0       0       0
    < chrI      113420  114870  peak_5  0       .       113440  114700  0       1       1260    20      0       0       0
    < chrI      140480  142080  peak_6  0       .       140760  141740  0       1       980     280     0       0       0
    < chrI      165050  165900  peak_7  0       .       165330  165830  0       1       500     280     0       0       0
    < chrI      181160  181650  peak_8  0       .       181200  181610  0       1       410     40      0       0       0
    < chrI      198460  199140  peak_9  0       .       198660  199090  0       1       430     200     0       0       0
    < chrI      60130   62600   peak_2  0       .       60410   62150   0       1       1740    280     0       0       0
    < chrI      67960   69780   peak_3  0       .       68160   69260   0       1       1100    200     0       0       0
    < chrI      71790   73230   peak_4  0       .       72120   73000   0       1       880     330     0       0       0
    16.18.4 checking hmmratac hmmratac_yeast500k_load_training_regions_accessible_regions.gappedPeak ...
     ... failed! Difference:
    1,283c1,919
    < chrI      0       700     peak_1  0       .       30      560     0       1       530     30      0       0       0
    < chrI      113420  114870  peak_5  0       .       113440  114700  0       1       1260    20      0       0       0
    < chrI      140480  142080  peak_6  0       .       140760  141740  0       1       980     280     0       0       0
    < chrI      165050  165900  peak_7  0       .       165330  165830  0       1       500     280     0       0       0
    < chrI      181160  181650  peak_8  0       .       181200  181610  0       1       410     40      0       0       0
    < chrI      198460  199140  peak_9  0       .       198660  199090  0       1       430     200     0       0       0
    < chrI      60130   62600   peak_2  0       .       60410   62150   0       1       1740    280     0       0       0
    < chrI      67960   69780   peak_3  0       .       68160   69260   0       1       1100    200     0       0       0
    < chrI      71790   73230   peak_4  0       .       72120   73000   0       1       880     330     0       0       0

**To Reproduce**
You might like to run

    cd test
    ./cmdlinetest macs3.0.0-1-3.12

(same with `macs3.0.0-1-3.11` which is macs3.0.0 built against Python3.11) on a Debian unstable system (container)

**Expected behavior**
I confirm

    python3.12 -m pytest test

(or `python3.11`) is working but the `cmdlinetest` shows these failures.  I wonder if just some data need to be justified due to some rounding errors?

**System (please complete the following information):**
 - OS: Debian unstable
 - Python version: 3.11 or 3.12
 - Numpy version: 1.24.2
 - MACS Version: 3.0.0

**Comment by taoliu** [comment] 2024-01-29 20:46
Hi @tillea, We had a similar issue due to the Numpy version. The same code of MACS will generate slightly different results in Numpy with version < 1.25 and version >=1.25. The current standard output for testing (`cmdlinetest`) is from Numpy 1.25. Did you see such an issue in other Python-based tools that depend on Numpy?

**Comment by tillea** [comment] 2024-01-29 21:26
Hi,

it happens from time to time that version bumps of numpy lead to minor differences.  In general I'd recommend to relax precision of tests in general since this might also happen on different hardware architectures.

Kind regards, Andreas.

**Comment by taoliu** [comment] 2024-01-31 22:32
@tillea  we tested using Github Action: https://github.com/macs3-project/MACS/actions/runs/7732237695/job/21083012078 for python3.11 and numpy 1.24.2, and the test passed. It may also relate to other dependencies as well. I think the only way to solve this is to relax the test -- we relaxed the precision of tests before. But this time, the differences in the result are at the peak coordinates -- usually 1bp difference. It's trivial to go through each peak coordination and allow a 1bp difference. Perhaps we can use other criteria to test that the results are 'similar' to the standard. Let me think...

**Comment by tillea** [comment] 2024-02-01 06:29
Thanks a lot for your invesigation.  Please ping me if you've found some solution.

**Comment by taoliu** [comment] 2024-02-16 16:50
@tillea Here are some updates. We have made a script to calculate the Jaccard index of two sets of peaks, so if there are some tiny differences between them, our testing script can tolerate them -- [jaccard.py](https://github.com/macs3-project/MACS/blob/feat/macs3/test_peak_overlap/test/jaccard.py) and a updated [cmdlinetest](https://github.com/macs3-project/MACS/blob/feat/macs3/test_peak_overlap/test/cmdlinetest). We also tested and decided to include scipy and scikit-learn into the list of dependencies since the HMM module (hmmlearn) needs them. `hmmlearn` asks for pretty old scikit-learn (version before 1.0) and it will cause inconsistency of `hmmratac` output from MACS3, so we explicitly require certain version of scikit-learn and scipy in pyproject.toml. We should release a 3.0.1 version with these changes. 

Also, since we just figured out that the `hmmratac` output can be impacted by different `scipy` and `scikit-learn` version. Could you provide the versions of them in your testing system so that we can exactly reproduce the 'slightly different' output that you saw?

**Comment by tillea** [comment] 2024-02-17 09:56
Thanks a lot for relaxing the tests.
We are using
 
     scipy 1.11.4
     sklearn 1.2.1

currently.  I think when the error showed up first time we were at scipy 1.10.
Usually you can see a full build log in our CI but this does not work for whatever reason for MACS.  Sorry about this.

**Comment by taoliu** [comment] 2024-02-19 03:23
Thanks! Finally, find the cause of inconsistent results from `hmmratac`. Please see the PR #620: in brief, `hmmlearn` needs to be patched https://github.com/hmmlearn/hmmlearn/pull/545 because of the [1.3.0 update](https://scikit-learn.org/1.3/whats_new/v1.3.html) of sklearn where the results from Kmeans will be not consistent with the results from older sklearn. The idea is to do the random seeding for 10 times and pick the best one. We implemented the patch in the MACS3/Signal/HMMR_HMM.pyx for now and hopefully `hmmratac` will include this change, https://github.com/hmmlearn/hmmlearn/pull/545,  in the next release since it's already merged to its main branch. As a result, the difference due to sklearn [1.2](https://github.com/macs3-project/MACS/actions/runs/7951944392/job/21705969257) and [1.3](https://github.com/macs3-project/MACS/actions/runs/7951982836/job/21706050015) is small enough and can be tolerated by our new `jaccard.py` tool:

`... success! Results are different but Jaccard Index is 1.0 (>0.99)`

Will aim at releasing a new version MACS3 in the next week and please let me know if it can pass the test on debian med.

**Comment by taoliu** [comment] 2024-02-23 15:22
@tillea MACS3 has been updated to v3.0.1 with changes to address this issue. Please let us know if it can pass the test on Debian.

**Comment by mr-c** [comment] 2024-02-23 16:38
@taoliu Thank you for the v3.0.1 release! I'm seeing the following with Python 3.12:

```
  checking the files: ../temp/macs3.0.1-1-3.11_run_hmmratac/hmmratac_yeast500k_accessible_regions.gappedPeak vs standard_results_hmmratac/hmmratac_yeast500k_accessible_regions.gappedPeak
 ... failed! Results are different and Jaccard Index is 0.2775891758917589 (<0.99)
16.18.2 checking hmmratac hmmratac_yeast500k_bedpe_accessible_regions.gappedPeak ...
  checking the files: ../temp/macs3.0.1-1-3.11_run_hmmratac/hmmratac_yeast500k_bedpe_accessible_regions.gappedPeak vs standard_results_hmmratac/hmmratac_yeast500k_bedpe_accessible_regions.gappedPeak
 ... failed! Results are different and Jaccard Index is 0.2775891758917589 (<0.99)
16.18.3 checking hmmratac hmmratac_yeast500k_load_hmm_model_accessible_regions.gappedPeak ...
  checking the files: ../temp/macs3.0.1-1-3.11_run_hmmratac/hmmratac_yeast500k_load_hmm_model_accessible_regions.gappedPeak vs standard_results_hmmratac/hmmratac_yeast500k_load_hmm_model_accessible_regions.gappedPeak
 ... failed! Results are different and Jaccard Index is 0.2775891758917589 (<0.99)
16.18.4 checking hmmratac hmmratac_yeast500k_load_training_regions_accessible_regions.gappedPeak ...
  checking the files: ../temp/macs3.0.1-1-3.11_run_hmmratac/hmmratac_yeast500k_load_training_regions_accessible_regions.gappedPeak vs standard_results_hmmratac/hmmratac_yeast500k_load_training_regions_accessible_regions.gappedPeak
 ... failed! Results are different and Jaccard Index is 0.2775891758917589 (<0.99)
```

The Python packages installed are
```
# python3.12 -m pip freeze
WARNING: Skipping /usr/lib/python3.12/dist-packages/numpy-1.24.2.egg-info due to invalid metadata entry 'name'
build==1.0.3
cykhash==2.0.0
Cython==3.0.8
decorator==5.1.1
hmmlearn==0.0.0
iniconfig==1.1.1
installer==0.7.0
joblib==1.3.2
numpy==1.24.2
packaging==23.2
pluggy==1.4.0
pyproject_hooks==1.0.0
pytest==7.4.4
scikit-learn==1.4.1.post1
SciPy==1.11.4
setuptools==68.1.2
threadpoolctl==3.1.0
toml==0.10.2
wheel==0.42.0
pyproject_hooks==1.0.0
pytest==7.4.4
scikit-learn==1.4.1.post1
SciPy==1.11.4
threadpoolctl==3.1.0
toml==0.10.2
```

Here are the temp directory contents: https://people.debian.org/~crusoe/macs3.0.1-1-tests_temp.tgz

**Comment by philippadoherty** [comment] 2024-02-23 17:18
Hi @mr-c  in our requirements we define `hmmlearn>=0.3` so this `hmmlearn==0.0.0` is strange to me, was hmmlearn not installed?

**Comment by mr-c** [comment] 2024-02-23 17:24
> Hi @mr-c in our requirements we define `hmmlearn>=0.3` so this `hmmlearn==0.0.0` is strange to me, was hmmlearn not installed?

Hmm.. maybe a `pip` issue. The installed version is 0.3.0-4

```
/# dpkg -l python3-hmmlearn
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version      Architecture Description
+++-================-============-============-===========================================================
ii  python3-hmmlearn 0.3.0-4      amd64        unsupervised learning and inference of Hidden Markov Models
```

**Comment by taoliu** [comment] 2024-02-23 17:43
Hi Michael @mr-c, Could you let me know how you managed to let numpy1.24 be installed with python3.12 since 'distutils' has been removed in 3.12?

**Comment by mr-c** [comment] 2024-02-23 17:46
@taoliu It seems that doesn't cause a problem for the [Debian 1.24.2-2 package of numpy](https://packages.debian.org/sid/python3-numpy)

https://salsa.debian.org/python-team/packages/numpy/-/blob/master/debian/changelog?ref_type=heads#L36

**Comment by mr-c** [comment] 2024-02-23 18:00
Here's a `Dockerfile` you can use to reproduce the build failure

First, check out our copy of MACS3 with the `debian/` directory added:
`git clone https://salsa.debian.org/med-team/macs.git`

``` Dockerfile
FROM docker.io/debian:sid

RUN apt-get update && apt-get install -y build-essential python3-all-dev python3-numpy python3-setuptools python3-pip python3-pytest python3-cykhash python3-hmmlearn libsimde-dev cython3 procps bc debhelper dh-sequence-python3 pybuild-plugin-pyproject help2man

COPY . /build

WORKDIR /build

RUN debian/rules binary
```

**Comment by taoliu** [comment] 2024-02-23 20:14
@mr-c OK. Now I can reproduce the error and found the problem. The thing is that debian/python-hmmlearn has already incorporated some un-released patches from upstream (https://salsa.debian.org/med-team/python-hmmlearn/-/commit/2fe0fa06f874641b2b9ac16c6d7f038ecc9bef97), my simple patch on HMMR_HMM.pyx (I overrides an initiation function in hmmlearn.hmm.GaussianHMM) will have negative effects. Here is the solution. As for packaging MACS3 in Debian, Please patch the file  `MACS3/Signal/HMMR_HMM.pyx` :

```
--- HMMR_HMM.old.pyx	2024-02-23 15:10:39
+++ HMMR_HMM.pyx	2024-02-23 15:11:09
@@ -90,7 +90,7 @@
     # according to base documentation, if init_prob not stated, it is set to be equally likely for any state (1/ # of components)
     # if we have other known parameters, we should set these (ie: means_weights, covariance_type etc.)
     rs = np.random.RandomState(np.random.MT19937(np.random.SeedSequence(random_seed)))
-    hmm_model = GaussianHMM_modified( n_components= n_states, covariance_type = covar, random_state = rs, verbose = False )
+    hmm_model = hmm.GaussianHMM( n_components= n_states, covariance_type = covar, random_state = rs, verbose = False )
     hmm_model = hmm_model.fit( training_data, training_data_lengths )
     assert hmm_model.n_features == 4
     return hmm_model
@@ -121,7 +121,7 @@
 cpdef list hmm_model_init( str model_file ):
     with open( model_file ) as f:
         m = json.load( f )
-        hmm_model = GaussianHMM_modified( n_components=3, covariance_type=m["covariance_type"] )
+        hmm_model = hmm.GaussianHMM( n_components=3, covariance_type=m["covariance_type"] )
         hmm_model.startprob_ = np.array(m["startprob"])
         hmm_model.transmat_ = np.array(m["transmat"])
         hmm_model.means_ = np.array(m["means"])
```

**Comment by mr-c** [comment] 2024-02-24 11:27
@taoliu Thank you for the patch and for having such good test coverage to catch these issues! I can confirm the fix, this issue can be closed.

Do you know the hmmlearn people? Seems like they need a new release..

Sorry for forgetting the `QUILT_PATCHES` trick, I'm impressed that you figured that out!

**Comment by taoliu** [comment] 2024-02-24 15:27
@mr-c I don't know hmmlearns people, but I agree that we'd better ask them to have a new release -- even just a minor version update. The more I look at my simple overwritten code the more I dislike it.

I have an AI assistant to help me with debugging codes that I am not familiar with :)

**Closed** 2024-02-24 16:38 UTC
Labels: Bug Report
